@startuml
skinparam ClassAttributeIconSize 0
Class SinglePatternDemo
{
<b>public main()</b>
}
class SingleObject
{
 -Instance : SingleObject
 -SingleObject()
 +getInstance():SingleObject
 +showMessage() :void
}

SinglePatternDemo --> SingleObject :asks
SingleObject --> SingleObject :returns

@enduml